### ISSUE TITLE
youtube2ios

### ISSUE THREAD

**Issue by happyhappyhappyhappy** [happyhappyhappyhappy/pythoncode#7]
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/FB12D8F1-8CE3-4DFA-9906-117C895CCB93/Pythonista3/Documents/youtubedl/main.py", line 1, in <module>
    from pytube import YouTube
  File "/private/var/mobile/Containers/Shared/AppGroup/FB12D8F1-8CE3-4DFA-9906-117C895CCB93/Pythonista3/Documents/site-packages-3/pytube/__init__.py", line 16, in <module>
    from pytube.streams import Stream
  File "/private/var/mobile/Containers/Shared/AppGroup/FB12D8F1-8CE3-4DFA-9906-117C895CCB93/Pythonista3/Documents/site-packages-3/pytube/streams.py", line 17, in <module>
    from pytube import extract
  File "/private/var/mobile/Containers/Shared/AppGroup/FB12D8F1-8CE3-4DFA-9906-117C895CCB93/Pythonista3/Documents/site-packages-3/pytube/extract.py", line 7, in <module>
    from pytube.compat import quote
ImportError: cannot import name 'quote'

**Comment by happyhappyhappyhappy** [comment]
from pytube import YouTube
に使うpytubeをpytube3にすればよい。
が、これは参照元のサイトの参考サイトのコピペに過ぎないのでコメントアウトしてもよい。
その延長でmy_moduleも邪魔なのでコメントアウトしたら通った。
youtube_dlの機能については色々調べたい。
